version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: MyDb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    networks:
      - my-network

  postgres:
    image: postgres:12-alpine
    container_name: PostgreDb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgredb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    networks:
      - my-network

  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    image: node-app:1.0
    container_name: Node-app
    ports:
      - '9999:9999'
    command: sh -c "sleep 40 && npm start"
    depends_on:
      - postgres
      - mysql
    networks:
      - my-network

networks:
  my-network: